# addons:
#   apt:
#     packages:
#       - libgsl2
#       - gsl-bin
#       - libgsl-dev
#       - libmagick++-dev

# Undid replacement of replaced libgsl2 with libgslcblas0

language: r
cache: packages
sudo: required
# Be strict when checking our package

# Eh, let's be less strict at first
warnings_are_errors: false


before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libmagick++-dev
- sudo apt-get install libgmp3-dev
- export RGL_USE_NULL=TRUE

script:
- R CMD build .
- travis_wait 45 R CMD check *tar.gz --as-cran

# for code coverage
r_packages:
  - covr

after_success:
  -  travis_wait 45 Rscript -e 'covr::codecov()'
  
  
  