language: r
cache: packages
warnings_are_errors: TRUE

before_install:
- sudo apt-get install libgmp3-dev
- export RGL_USE_NULL=TRUE 

script:
- R CMD build .
- travis_wait 55 R CMD check *tar.gz --as-cran
  
after_success:
  - Rscript -e 'covr::codecov()'
