addons:
  apt:
    packages:
      - libgsl2
      - gsl-bin
      - libgsl-dev
      - libmagick++-dev

language: r
sudo: required
# Be strict when checking our package
warnings_are_errors: true


before_install:
- sudo apt-get install libgmp3-dev
- export RGL_USE_NULL=TRUE

script:
- R CMD build .
- travis_wait 45 R CMD check *tar.gz --as-cran

# for code coverage
r_packages:
  - covr

after_success:
  -  travis_wait 45 Rscript -e 'covr::codecov()'
  
  
  